/* Macro zur Erstellung der Basic Description
nummerische Variable: PROC MEANS
Kategorie-/Text-Variable: PROC FREQ
*/
libname n1201 "E:\SDT-RP-11223\files_NVT_SA_FTY720D1201\Files\Analysis Ready Datasets\SAS_analysis";
libname n1201e1 "E:\SDT-RP-11223\files_NVT_SA_FTY720D1201E1\Files\Analysis Ready Datasets\SAS_analysis";
libname n2301 "E:\SDT-RP-11223\files_NVT_SA_FTY720D2301\Files\Analysis Ready Datasets\SAS_analysis";
libname n2302 "E:\SDT-RP-11223\files_NVT_SA_FTY720D2302\Files\Analysis Ready Datasets\SAS_analysis";
libname n2309 "E:\SDT-RP-11223\files_NVT_SA_FTY720D2309\Files\Analysis Ready Datasets\SAS_analysis";
libname r92p1 "E:\SDT-RP-11223\files_RCH-WA21092-PRIM1\Files\Analysis Ready Datasets\SAS_analysis";
libname r92p2 "E:\SDT-RP-11223\files_RCH-WA21092-PRIM2\Files\Analysis Ready Datasets\SAS_analysis";
libname r93p1 "E:\SDT-RP-11223\files_RCH-WA21093-PRIM1\Files\Analysis Ready Datasets\SAS_analysis";
libname r93p2 "E:\SDT-RP-11223\files_RCH-WA21093-PRIM2\Files\Analysis Ready Datasets\SAS_analysis";
libname r93ud "E:\SDT-RP-11223\files_RCH-WA21493-UPDT\Files\Analysis Ready Datasets\SAS_analysis";
libname s223  "E:\SDT-RP-11223\files_SAN-CAMMS223\Files\Datasets_CAMMS223";
libname s323  "E:\SDT-RP-11223\files_SAN-CAMMS323\Files\Datasets_CAMMS323";
libname s507  "E:\SDT-RP-11223\files_SAN-CAMMS32400507\Files\Datasets_CAMMS32400507";

%macro basicdesc(study,sheet,ds,vars1,vars2);
/*  study  - Study-Lib-Name
    sheet  - domain (only for file name)
    ds     - Datasetname
    vars1  - Variablenliste mit nummerischen Variablen (PROC MEANS)
    vars2  - Variablenliste mit Kategorie-/Textvariablen (PROC FREQ)
    Ausgabe als RTF-File
*/
    ods rtf file = "D:\Users\mse0jxh8\Documents\My SAS Files\9.4\basic\&study._&sheet._&ds..rtf" style=styles.journal bodytitle startpage = YES;
    options nodate;
    %let var_list = &vars1.
                    ;
	%let b=1;
	%do %while(%scan(&var_list.,&b.) ne );
	    %let y = %scan(&var_list.,&b.);

		title1 height = 16pt  bold "Variable &y.";

        proc means data = &study..&ds. n min q1 mean median q3 max;
            var &y.;
        run;

	    %let b = %eval(&b. + 1);
	%end;

    %let var_list = &vars2.
                    ;
	%let b=1;
	%do %while(%scan(&var_list.,&b.) ne );
	    %let y = %scan(&var_list.,&b.);

		title1 height = 16pt  bold "Variable &y.";

        proc freq data = &study..&ds.;
            tables &y. /MISSING;
        run;

	    %let b = %eval(&b. + 1);
	%end;

	ods rtf close;
%mend basicdesc;

%basicdesc(N1201,AE,A_AEINF_MSE,DAYNI_1N,
                     ACNTAK3N AEVNAM1A AEVSER1C AEVSTT1O day_1n day_3n DAYNI_1N dystt_1n EXT1N MHLGCODE MHLTCODE MLLTCODE 
                     MPTCODE NMLCOD1A RPEVIS1N SBJ1N SID1A SOC_ABBR STY1A VIS1N);
%basicdesc(R92P1,AE,AAE,AESTDY APERIOD,
                     AEBODSYS AECAT AEHLGT AEHLGTCD AEHLT AEHLTCD AELLT AELLTCD AESDTH AESER AESHOSP AESLIFE AESMIE AESOCCD
                     AESTDY ANLFL APERIOD APERIODC GINFOVER GMALOVER GPREMAL STUDYID USUBJID);
%basicdesc(S223,AE,ADAE,AEMONTH AESTDY,
                     AEACN AEBODSYS AEDECOD AEHLGT AEHLT AELLT AEMONTH AEOUT AESER AESTDT AESTDY STUDYID SUBJID USUBJID);

%basicdesc(N1201,CoMed,A_CMDATC_MSE,,
                     ATC_TXT ATCCODE CMDEND1D CMDEND1O CMDSTT1D CMDSTT1O CONCTIM DAY_1N DRUGCODE DYSTT_1N EXT1N IT_TXT
                     NDGCOD1A RPEVIS1N SBJ1N SID1A STY1A VIS1N);
%basicdesc(R92P1,CoMed,ACM,APERIOD CMEDY CMSDY,
                     ANLFL APERIOD APERIODC CMCAT CMCLAS CMDECOD CMDECOD2 CMEDY CMMSFL CMOCCUR CMSCAT CMSDY STUDYID USUBJID);
%basicdesc(S223,CoMed,ADCM,CMENDY CMSTDY,
                      ADCMCLAS CMCAT CMDECOD CMENDTC CMENDY CMSTDTC CMSTDY MSFL PMFL STUDYID SUBJID USUBJID);

%basicdesc(N1201,CoDis,A_CND_MSE,DAY_1N DYVIS_1N,
                     ACTPRB1C DAY_1N DGNSRG1D DGNSRG1O DYVIS_1N EXT1N HISCND1A HLT_TXT LLIT_TXT MHLGCODE MHLTCODE MLLTCODE
                     MPTCODE NMLCOD1A PSTBL_1C PT_TXT RPEVIS1N SBJ1N SID1A STY1A VIS1N);
%basicdesc(R92P2,CoDis,AMH,MHEDY MHSDY,
                     MHCAT MHDECOD MHDISTAT MHEDY MHOCCUR MHPRESP MHPTCD MHSDY MHTIREL STUDYID USUBJID);
*%basicdesc(S223,CoDis,ADCM,,
                      );

%basicdesc(N1201,IDENT,A_IDENT_MSE,AGE_1N EDSSCB EXDSC1NB LES_T1BC NUMRLP2N WGT_1N,
                     AGE_1N BMI_1N DCNRSN1C DCNRSN2C DCNRSN3C DOB1O DTH1D DTH1O DURDISYR EDSSCB EXDSC1NB FAS HGT_1N LES_T1BC 
                     LSTD1D LSTD1O M_FAS NUMRLP2N PP PRIORMS RCE5C RDP SAFETY SBJ1N SBJCMP3C SBJSTA1C SEX1C SID1A TGP1A
                     TGPDSC1A TRTN TRTREG1C WGT_1N);
%basicdesc(R92P1,IDENT,ADSL,B9HPT BAGE BAMBL BBMI BBOBL BBRAI BCERB BCERE BCGMV BEDSS BFCS BGDLES BHT BNVOL
                     BPASAT BPYRD BSDMT BSENS BT1LES BT25FW BT2LES BT2VOL BVISU BWMV BWT NRLP ONSETDUR
                     RLP1YR RLP2YR,
                     ARM ARMCD B9HPT BAGE BAGEU BAMBL BBMI BBOBL BBRAI BCERB BCERE BCGMV BEDSS BFCS BGDLES BHT BHTU BNVOL
                     BPASAT BPYRD BSDMT BSENS BT1LES BT25FW BT2LES BT2VOL BVISU BWMV BWT BWTU ITTFL NRLP ONSETDUR PPFL
                     PRVMSFL RACE RLP1YR RLP2YR SAFFL SEX STUDYID STYDISFL STYDISRS TRT01A TRT01P USUBJID);
%basicdesc(S223,IDENT,ADSL,AGE BMIBL EDSSBL HEIGHTBL M36STDY NCE1 NCE2 NCE3
                      T1VOLBL T2VOLBL TMSIEP WEIGHTBL,
                      AGE AGECATDI AGEU ARM ARMCD BMIBL DSREAS EDSSBL FAFL FAFN HEIGHTBL ITPFL ITPFN M36STDY NCE1 NCE2 NCE3
                      RACE RACEN SEX SEXN STUDYID SUBJID T1VOLBL T2VOLBL TMSIEP TRTA TRTAN TRTP TRTPN USUBJID WEIGHTBL);

%basicdesc(N1201,EDSS,A_EDSS_MSE,DAYNI_1N EXDNCHG EXDSC1N EXDSC1NB FUNBOW1N
                     FUNBRA1N FUNCER1N FUNMEN1N FUNOTH1C FUNPYR1N FUNSEN1N FUNVSU1N,
                     DAYNI_1N DURREL EXDNCAT EXDNCHG EXDSC1N EXDSC1NB EXMDAT1D EXMDAT1O EXT1N FLAGFSE FLGBASE FUNBOW1N
                     FUNBRA1N FUNCER1N FUNMEN1N FUNOTH1C FUNPYR1N FUNSEN1N FUNVSU1N RPEVIS1N SBJ1N SID1A STY1A VIS1N VIS2N);
%basicdesc(R92P1,EDSS,AEDSS,ADY APERIOD AVAL CHG QSSTRESN,
                     ABLFL ADY ANLFL APERIOD APERIODC AVAL AVALC AVISIT CHG CHGCAT PARAM PARAMCD QSORRES QSRESCAT QSSCAT
                     QSSTRESC QSSTRESN QSTEST QSTESTCD STUDYID USUBJID VISIT VISITNUM);
%basicdesc(S223,EDSS,ADNS,AVAL BASE,
                     AVAL AVISITC AVISITN BASE DOMAIN PARAM PARAMCAT PARAMCD RSP RSPN STUDYID SUBJID USUBJID);

%basicdesc(N1201,MRI,A_MRI_MSE,NUMGD1BA NUMGDT1 NUMNNT2,
                     EXT1N FLAGMRI FRET2M3 FRET2M6 NUMGD1BA NUMGDT1 NUMNNT2 SBJ1N SID1A STY1A VIS1N VIS2N);
%basicdesc(R92P2,MRI,AMRI,APERIOD AVAL ZDSEQ ZDSTRESN,
                     APERIOD APERIODC AVAL AVALC AVALU AVISIT AVISITN BASE PARAM PARAMCD STUDYID USUBJID ZDCAT
                     ZDORRES ZDORRESU ZDSEQ ZDSTRESC ZDSTRESN ZDSTRESU ZDTEST ZDTESTCD);
%basicdesc(S223,MRI,ADMR,ANLDY BASE,
                     ANLDY ANLFL AVISITC AVISITN BASE PARAM PARAMCAT PARAMCD STUDYID SUBJID USUBJID);

%basicdesc(N1201,Rlps,A_REL_MSE,ARLNUM1 ARLNUM1i ARLNUM2 DAY_1N DAY_3N INSTUDY1 RELNUM1 RELNUM1i RELNUM2 RELNUM2c,
                     ARELFRE1 ARLNUM1 ARLNUM1i ARLNUM2 DAY_1N DAY_3N EXR1C EXT1N INSTUDY1 RELFREE1 RELNUM1 RELNUM1i
                     RELNUM2 RELNUM2c RELSTT1D RELSTT1O RLPCFM1C SBJ1N SID1A STY1A VIS1N);
%basicdesc(R92P2,Rlps,ARLP,AENDY ASTDY,
                     AENDY ASTDY AVALC PARAM PARAMCD STUDYID SYBRAIFL SYCERBFL SYCEREFL SYFATGFL SYOTHFL SYOTHSP
                     SYPYRDFL SYSENSFL SYVISUFL USUBJID);
%basicdesc(S223,Rlps,ADREL,LREFLYR REFLTIME REFLYR RENUM RETIME RETIME1 RETIME2,
                     HADRE LREFLYR RECAT RECNTFL REDT REDTC REFLTIME REFLYR RENUM REPRFL RETIME RETIME1 RETIME2
                     RFENDT RFENDTC RFSTDT STUDYID SUBJID USUBJID);

%basicdesc(N1201,Others,A_MSHIS_MSE,NUMRLP1N NUMRLP2N TIMLSTD TMTDUR,
                     ATC_TXT ATCCODE DCNRSN5C DURDISYR DURMS1 EXT1N HISMSL1C HISMSL2C HISMSL3C HISMSL4C HISMSL5C
                     NUMRLP1N NUMRLP2N PRVTMT8C SBJ1N SID1A STY1A TIMLSTD TMTDUR VIS1N);
*%basicdesc(R92P2,Others,,,
                     );
%basicdesc(S223,Others,ADMS,AVAL BASE,
                     ABLFL AVAL AVISITC AVISITN BASE PARAM PARAMCAT PARAMCD RFENDT RFENDTC RFSTDT RFSTDTC STUDYID
                     SUBJID USUBJID VISIT);

%basicdesc(N1201,Ophta,A_OPHHIS_MSE,,
                     medema neubilat neurecur neuritis neusnepi neuunlat sbj1n sid1a sty1a uveitis);
%basicdesc(N1201,Ophta,A_OPH_MSE,DAYNI_1N EQV1N EQV2N FLUORDAY OCTCFBN OCTCFTN OCTSD1C OCTSS1N VADEC1N VADECAVF,
                     ASMC CFTCAT CFTCATCG DAYNI_1N DOPAD1C DOPFLG EQV1N EQV2N EVLEYE1C EXT1N FAAD1C FAME1C FARCL1C FLAFLG
                     FLUORDAY MCU2C MCUEDM MEOAD1C MEOFLG MEOFUP1C MEOME1C MEOMESC MEOMEUC MEOTRT1C MEOVISC OCTAD1C
                     OCTCFBN OCTCFTN OCTEAD1C OCTFLG OCTSD1C OCTSS1N OCTTYP1A OCTTYP1C OPHBASEN OPHDAT1D OPHDAT1O
                     OPHDAT2D OPHDAT2O OPHLSTAS OPHONTRT OTH1A RPEVIS1N SBJ1N SID1A SPY1A STY1A VAAD1C VADEC1N VADECAV
                     VADECAVF VATESTC VIS1N VISNAM1A VSA3C VSATST2C VSUSYM1C);
%basicdesc(R92P2,Ophta,ALCVA,AVAL BASE ZASEQ ZASTRESN,
                     ABLFL ANLFL AVAL BASE DOMAIN PARAM PARAMCD STUDYID USUBJID VISIT VISITNUM ZAORRES ZASEQ ZASTRESC
                     ZASTRESN ZATEST);
%basicdesc(S223,Ophta,ADPR,AVAL BASE,
                     ABLFL AVAL AVALC AVISITC AVISITN BASE DOMAIN PARAM PARAMCAT PARAMCD STUDYID SUBJID USUBJID VISIT);

%basicdesc(N1201,Lab,A_LRS_MSE,BLVAL_1N CV_BL_1N LABRSL1N,
                     BLFLG_1C BLVAL_1N CV_BL_1N CVUNT_1C EXT1N LABCAT1C LABRSL1C LABRSL1N MTYPE_1C PARNAM1C PARUNT1C
                     PREUNT1C PSTBL_1C RPEVIS1N SBJ1N SID1A STY1A VIS1N);
%basicdesc(R92P1,Lab,ALB,AVAL LBSTRESN,
                     ABLFL ANLFL APERIOD APERIODC AVAL AVALU LBCAT LBCOGBFL LBSTRESN LBSTRESU PARAM PARAMCD STUDYID
                     USUBJID VISIT VISITNUM);
%basicdesc(S223,Lab,ADLB,BASE1,
                     AVISITC AVISITN BASE1 CYCNUM DOMAIN PARAM PARAMCAT PARAMCD STUDYID SUBJID USUBJID VISIT);
